v-01 f-01 add task
Artem-spec/carsharing-admin pull request #1
Opened 2021-11-08 17:12 UTC by Artem-spec

2021-11-10 07:32 UTC, chugunovns21 requested changes

2021-11-10 07:32 UTC, chugunovns21 commented on src/App.js
> +        } else history.push('/admin');
Лучше добавлять фигурные скобки в такой конструкции - повышает читаемость кода)

2021-11-10 07:32 UTC, chugunovns21 commented on src/components/AdminPanel/AdminPanel.js
> +                        </g>
Лучше выносить svg в отдельный файл, который лежит в папке img и импортировать оттуда

2021-11-10 07:32 UTC, chugunovns21 commented on src/components/Authorization/FormAuthorization/FormAuthorization.js
> +        };
Обычно такие функции выносятся в отдельный файл и импортируются в компонент

2021-11-10 07:32 UTC, chugunovns21 commented on src/components/Logo/Logo.js
> +            />
В отдельный файл

2021-11-10 07:32 UTC, chugunovns21 commented on src/components/AdminPanel/AdminPanel.js
> +const AdminPanel = () => {
Весь этот фаил нужно разбить на отдельные компоненты, вроде хедера, футера, меню и основного блока

2021-11-10 14:28 UTC, Artem-spec commented on src/App.js
> +        } else history.push('/admin');
Исправлено.

2021-11-10 14:48 UTC, Artem-spec commented on src/components/AdminPanel/AdminPanel.js
> +                        </g>
Исправлено.

2021-11-10 14:57 UTC, Artem-spec commented on src/components/Logo/Logo.js
> +            />
Исправлено

2021-11-10 15:24 UTC, Artem-spec commented on src/components/AdminPanel/AdminPanel.js
> +const AdminPanel = () => {
Исправлено

2021-11-10 18:46 UTC, Artem-spec commented on src/components/Authorization/FormAuthorization/FormAuthorization.js
> +        };
Исправлено.

2021-11-12 06:37 UTC, chugunovns21 commented
![image](https://user-images.githubusercontent.com/63374297/141421603-a6f77e39-48b7-4a30-ad27-799d6e714352.png)
Думаю, что лучше вынести футер из меин компонента, чтобы хедер, мейн и футер были на одном уровне.

2021-11-15 10:41 UTC, merged