v-08 v-09 f-10 add task
Artem-spec/carsharing-admin pull request #3
Opened 2021-11-23 17:51 UTC by Artem-spec

2021-11-24 14:04 UTC, EvgeniyaFilatova commented
- [ ] На планшете и мобиле при открытии меню лучше сделать, чтобы иконка менялась на крестик
![image](https://user-images.githubusercontent.com/90593835/143252905-9a67e8b7-7082-4e06-b991-fb67d89aad80.png)

2021-11-24 14:11 UTC, EvgeniyaFilatova commented
- [ ] На тех же разрешениях не очень удачная сетка для хедера: очень широкая получается. Лучше переместить блок с профилем (отображать на этих разрешениях только аватарку) и иконку со "звонком" (уведомления, наверное, какие-то) в шапку справа. Если не совсем будет помещаться, то логотип можно будет сдвинуть левее ближе к бургер-меню. Поиск я бы убирала на этих разрешениях в саму менюшку - в самом верху (не знаю, насколько это просто будет сделать), либо в хедер запихивать иконку "лупы", по нажатии на которую будет всплывать чуть ниже поле ввода (но возможно в хедере уже нет места для этой иконки), как еще вариант - оставлять всё-таки этот блок снизу хедера, только сделать его меньше по высоте
![image](https://user-images.githubusercontent.com/90593835/143254018-4e40942a-5d3a-4c6f-b0d4-616fbd8b16dd.png)

2021-11-24 14:13 UTC, EvgeniyaFilatova commented
- [ ] Нужно сделать, чтобы в фильтрах еще были варианты "любой", чтобы отображать все записи
![image](https://user-images.githubusercontent.com/90593835/143254353-cf214a61-5486-4ade-b3c5-a5f701cb1d2f.png)

2021-11-24 14:18 UTC, EvgeniyaFilatova commented
- [ ] Приведи в соответствие с макетом:
- отступы между картинкой и текстом
- размер шрифтов
- знак рубля в итоговой сумме
![image](https://user-images.githubusercontent.com/90593835/143255043-916b9342-7917-49ef-b900-84d85e6216a5.png)

2021-11-24 14:28 UTC, EvgeniyaFilatova commented
- [ ] В списке машин (и остальных сущностях) горизонтальный скролл выглядит не очень хорошо. У тебя в принципе этот скролл нужен только для машин, из-за того, что там много инфы. Давай либо совсем уберем самый большой блок (Описание), либо ограничим его по ширине пускай текст будет в несколько строк там. И тогда во всех таблицах сущностей нужно убрать отображение горизонтального скролла на десктопе, если такое возможно. На мобиле и планшете понятное дело нам его не избежать, но там нужно тогда, чтобы самый первый столбец при прокрутке вправо прилипал к левой стороне экрана, а то пока докрутишь до кнопок, уже потерял строку, которую хотел отредактировать, например
![image](https://user-images.githubusercontent.com/90593835/143256231-cd99f388-5651-45a5-b19a-aa183859041d.png)

2021-11-24 14:30 UTC, EvgeniyaFilatova commented
- [ ] На мобиле и планшете, когда у тебя появляется бургер-меню, при переходе между страницами это меню должно закрываться автоматически, а оно у тебя остается открытым

2021-11-24 14:56 UTC, EvgeniyaFilatova requested changes

2021-11-24 14:56 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Car/Car.js
> +                        {Boolean(pageItems.length) && (
- [ ] Можно не приводить явно с помощью Boolean, а оставить просто pageItems.length && - будет короче запись и в принципе понятная

2021-11-24 14:56 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Order/Order.js
> +                        {Boolean(pageItems.length) && (
- [x] То же самое (посмотри в других файлах тоже)

2021-11-24 14:56 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                            style={
- [ ] Наверное, можно без тернарника сделать? Через &&

2021-11-24 14:56 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                        ></div>
- [ ] Сделай самозакрывающийся тег

2021-11-24 14:56 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                                {' '}
- [ ] А что это за пустые строки?

2021-11-24 14:56 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                                Цвет:{' '}
- [ ] Вроде необязательно так явно указывать пробел. Попробуй просто поставить пробел и на этой же строчке <b

2021-11-24 18:11 UTC, Artem-spec commented on src/components/AdminPanel/Main/Car/Car.js
> +                        {Boolean(pageItems.length) && (
Исправлено

2021-11-24 18:13 UTC, Artem-spec commented on src/components/AdminPanel/Main/Order/Order.js
> +                        {Boolean(pageItems.length) && (
Исправлено

2021-11-25 13:05 UTC, Artem-spec commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                            style={
Исправлено

2021-11-25 13:05 UTC, Artem-spec commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                                Цвет:{' '}
Это pretter автоматом добавляет , я вынес так :   {` ${order.color}`}. Он настроен на удаление лишних пробелов.

2021-11-25 13:05 UTC, Artem-spec commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                                {' '}
Исправлено

2021-11-25 13:15 UTC, Artem-spec commented on src/components/AdminPanel/Main/Order/OrderCard/OrderCard.js
> +                            style={
Откатил обратно, возникает ошибка

2021-11-26 04:58 UTC, EvgeniyaFilatova commented
- [ ] Стили как будто слетели в мобильном меню. Как было раньше - было ок, просто нужно на крестик менять при открытии меню) И чтобы этот крестик был на том же месте, где и иконка "бургера", сейчас она у тебя сильно смещается
![image](https://user-images.githubusercontent.com/90593835/143529139-f522e1aa-5274-4c0f-b23d-433be18f69c2.png)

2021-11-26 04:59 UTC, EvgeniyaFilatova commented
- [ ] Сетку не перестроил в хедере, оставляй ее такой же, как на десктопе, просто компактнее располагай элементы. И можно блок с аватаркой уменьшить, оставить чисто аватарку без "Admin" и стрелочки
![image](https://user-images.githubusercontent.com/90593835/143529297-5d68098f-80be-499c-b64e-024224f9ac5a.png)

2021-11-26 05:01 UTC, EvgeniyaFilatova commented
- [ ] В списке городов верстка поехала
![image](https://user-images.githubusercontent.com/90593835/143529451-836329c3-bcd2-4713-9cb8-6c84aa9a4825.png)

2021-11-29 14:07 UTC, EvgeniyaFilatova commented
- [ ] Убери box-shadow у логотипа и элементов мобильного меню. В меню для разграничения элементов используй borde-bottom и тяни блоки на всю ширину контейнера
![image](https://user-images.githubusercontent.com/90593835/143882249-d29e3d34-4105-4992-b639-44abad45d9fb.png)
![image](https://user-images.githubusercontent.com/90593835/143882303-7e9704f8-1106-43ef-9692-d8c0571e2f20.png)

2021-11-29 14:09 UTC, EvgeniyaFilatova commented
- [ ] В адресах замени заголовок на "Адреса" и во всех таблицах отступ сделай между самой таблицей и заголовком
![image](https://user-images.githubusercontent.com/90593835/143882638-db586319-0626-4b79-a405-7686fec2ed19.png)

2021-11-29 14:14 UTC, EvgeniyaFilatova commented
- [ ] Еще по хорошему сделать выделение текущего пункта меню цветом каким-нибудь (лучше зеленым каким-нибудь, под цвет лого)

2021-11-29 14:28 UTC, merged