v10 v11 f09 add task
Artem-spec/carsharing-admin pull request #5
Opened 2021-11-30 17:44 UTC by Artem-spec

2021-12-01 11:10 UTC, EvgeniyaFilatova commented
- [ ] А какие требования к картинке, кроме того, что должна быть png (кстати, почему только такой формат)? Загружаю, а поле все равно подсвечивает красным
![image](https://user-images.githubusercontent.com/90593835/144224333-28dcb1e3-5d32-448c-bd53-68ce4a885ea4.png)

2021-12-01 11:14 UTC, EvgeniyaFilatova commented
- [ ] Так и не сделал выделение текущего пункта меню
![image](https://user-images.githubusercontent.com/90593835/144224897-3aa95794-9775-4630-a44a-c00e71f4eebe.png)

2021-12-01 11:29 UTC, EvgeniyaFilatova requested changes

2021-12-01 11:29 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Button/ButtonDelete/ButtonDelete.js
> +        axiosConfig.defaults.headers.common[
- [ ] Я думаю, это надо вынести, как у тебя было в файле getDataAPI.js, например

2021-12-01 11:29 UTC, EvgeniyaFilatova commented on src/components/AdminPanel/Main/Car/CarModify/CarModify.js
> +const defStateDataPost = {
- [ ] Мне кажется, что ты пошел очень сложным путем при работе с формами, у тебя один стейт, который модифицируется много где и при разных условиях. Лучше использовать готовые библиотеки для работы с формами, например, Formik. Перепиши с его помощью
https://formik.org/

2021-12-01 11:33 UTC, EvgeniyaFilatova commented
- [ ] Нужно расположить блок по центру. Возможно проблема в ширине какого-то из блоков. потому что обрати внимание, у тебя там появляется горизонтальный скролл на странице
![image](https://user-images.githubusercontent.com/90593835/144227240-0f692c59-37a0-494d-a749-4f375e6d3a0a.png)

2021-12-01 11:35 UTC, EvgeniyaFilatova commented
- [ ] На основных страницах тоже горизонтальный скролл небольшой
![image](https://user-images.githubusercontent.com/90593835/144227661-55912854-9404-469c-8d66-021a3bff6419.png)

2021-12-02 07:46 UTC, Artem-spec commented on src/components/AdminPanel/Main/Car/CarModify/CarModify.js
> +const defStateDataPost = {
Испралено

2021-12-02 07:46 UTC, Artem-spec commented on src/components/AdminPanel/Main/Car/CarModify/CarModify.js
> +const defStateDataPost = {
Исправлено

2021-12-02 08:28 UTC, Artem-spec commented on src/components/AdminPanel/Main/Button/ButtonDelete/ButtonDelete.js
> +        axiosConfig.defaults.headers.common[
Исправлено

2021-12-02 14:38 UTC, EvgeniyaFilatova commented on src/utils/getDataAPI.js
> +  if (!id) {
- [ ] Я правильно понимаю, что у тебя в одном добавление нового элемента и обновление уже существующего? Если да, то лучше разделить все-таки эти две функции, чтобы внутри не было условия, а то выглядит как-то не очень хорошо
- [ ] И еще, можно ли тут сделать как в твоих предыдущих функциях сразу return axiosConfig и так далее? Создавать и вызывать функцию тут же - тоже странное решение (для deleteData тоже посмотри)

2021-12-02 19:12 UTC, Artem-spec commented on src/utils/getDataAPI.js
> +  if (!id) {
Исправлено

2021-12-03 08:05 UTC, merged